### ISSUE TITLE
Ao salvar o favorito, incrementar o contador da entidade Video

### ISSUE THREAD

**Issue by pradoo159** [GrupoPosFIAP/TechVideoFlux#2]
- [ ] Recuperar o vídeos da base (mongo -findById)
- [ ] Incrementar o contador de favoritos (vídeos) 
- [ ] Adicionar na lista do usuário 
- [ ] Persistir a entidade vídeo
- [ ] Persistir a entidade usuário (salvar somente o ID do vídeo)

**Comment by kesaraujo** [comment]
Está feito com os testes unitários na **feature/teste-estatistica**
